// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oupywimlivvsvvsgpiqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91cHl3aW1saXZ2c3Z2c2dwaXFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDQ0MzQsImV4cCI6MjA2NTIyMDQzNH0.LQHSaTrzyXuRNb4rfSZSl-u5PODmO5ev2KmZr13HgPE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);